version: "3.2"

services:

  rabbitmq:
    image: rabbitmq:3.9.20-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./docker/rabbitmq/log/:/var/log/rabbitmq

  db:
    image: mariadb:10.6.8
    environment:
      - MARIADB_INITDB_SKIP_TZINFO=1
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
     - ./docker/mariadb/data/:/var/lib/mysql/
     - ./docker/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
